/* automatically generated by version.py - do not edit! */

#include "version.h"

static char version[] = "NKOHUT-TAYLROACH-DEVEL;PID-HARD;STEER-HARD;TAIL-HARD: Thu Aug 30 19:49:24 2012";

char* versionGetString(void) { return version; }
